- name: Install vim & neovim with homebrew
  homebrew: name={{ item }} state=present
  loop:
    - neovim
    - vim
  tags:
    - vim

- name: Create directories if they dont exist
  file: name={{ item }} state=directory recurse=yes
  loop:
    - "~/.config/nvim"
    - "~/.config/nvim/cache"
    - "~/.vim"
  tags:
    - vim

- name: Symlink ~/.vimrc from source {{ dotfiles_directory_path }}/.vimrc
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.vimrc", dest: "~/.vimrc" }
  tags:
    - vim

- name: Symlink ~/.config/nvim/init.lua from source {{ dotfiles_directory_path }}/.config/nvim/init.lua
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.config/nvim/init.lua", dest: "~/.config/nvim/init.lua" }
  tags:
    - vim

- name: Symlink ~/.config/nvim/lua from source {{ dotfiles_directory_path }}/nvim/lua
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.config/nvim/lua", dest: "~/.config/nvim/lua" }
  tags:
    - vim

- name: Symlink ~/.vim/coc-settings.json from source {{ dotfiles_directory_path }}/.vim/coc-settings.json
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.vim/coc-settings.json", dest: "~/.vim/coc-settings.json" }
  tags:
    - vim

- pip:
    name: neovim
  tags:
    - vim

- pip:
    name: neovim
    executable: pip3
  tags:
    - vim

- pip:
    name: pynvim
  tags:
    - vim

- pip:
    name: pynvim
    executable: pip3
  tags:
    - vim

- name: Install neovim npm package globally
  npm:
    name: neovim
    global: yes
  tags:
    - vim

- name: Install neovim gem
  become_user: lenny
  gem: name="neovim" state=latest
  tags:
    - vim

- name: Install language servers & linters with npm
  npm: name={{ item }} global=yes
  loop:
    - "typescript"
    - "typescript-language-server"
    - "vscode-langservers-extracted"
    - "eslint_d"
  tags:
    - vim

- name: Install language servers with homebrew
  homebrew: name={{ item }} state=present
  loop:
    - "efm-langserver"
  tags:
    - vim

- name: Clone Sumneko Lua Language Server
  git:
    repo: https://github.com/sumneko/lua-language-server
    dest: ~/.config/nvim/cache/lua-language-server
  tags:
    - vim

- name: Compile & Install Lua Language Server
  shell: cd ~/.config/nvim/cache/lua-language-server && git submodule update --init --recursive && cd 3rd/luamake && compile/install.sh && cd ../.. && ./3rd/luamake/luamake rebuild
  tags:
    - vim
