---
galaxy_info:
  role_name: spotify
  author: ldonnez
  description: Spotify is a digital music streaming service that gives you access to millions of songs, podcasts and videos from artists all over the world.
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
