- name: Add neovim-ppa/stable
  become: yes
  apt_repository:
    validate_certs: no
    repo: "ppa:neovim-ppa/stable"
    state: present

- name: Install vim & neovim with apt
  apt: name={{ item }} state=present
  become: yes
  loop:
    - neovim
    - vim
  tags:
    - vim

- name: Create directories if they dont exist
  file: name={{ item }} state=directory recurse=yes
  loop:
    - "~/.config/nvim"
    - "~/.config/nvim/backup"
    - "~/.config/nvim/swap"
    - "~/.config/nvim/undo"
    - "~/.config/nvim/cache"
    - "~/.vim"
    - "~/.vim/backup"
    - "~/.vim/swap"
    - "~/.vim/undo"
  tags:
    - vim

- name: Symlink ~/.vimrc from source {{ dotfiles_directory_path }}/.vimrc
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  loop:
    - { src: "{{ dotfiles_directory_path }}/.vimrc", dest: "~/.vimrc" }
  tags:
    - vim

- name: Symlink ~/.config/nvim/init.lua from source {{ dotfiles_directory_path }}/.config/nvim/init.lua
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.config/nvim/init.lua", dest: "~/.config/nvim/init.lua" }
  tags:
    - vim

- name: Symlink ~/.config/nvim/lua from source {{ dotfiles_directory_path }}/.config/nvim/lua
  file: src={{ item.src }} dest={{ item.dest }} state=link
  loop:
    - { src: "{{ dotfiles_directory_path }}/.config/nvim/lua", dest: "~/.config/nvim/lua" }
  tags:
    - vim

- name: Symlink ~/.vim/coc-settings.json from source {{ dotfiles_directory_path }}/coc-settings.json
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  loop:
    - { src: "{{ dotfiles_directory_path }}/.vim/coc-settings.json", dest: "~/.vim/coc-settings.json" }
  tags:
    - vim

- pip:
    name: neovim
    executable: pip3
  tags:
    - vim

- pip:
    name: neovim-remote
    executable: pip3
  tags:
    - vim

- pip:
    name: pynvim
    executable: pip3
  tags:
    - vim

- name: Install neovim npm package globally
  become_user: "{{ ansible_user_id }}"
  npm:
    name: neovim
    global: yes
  tags:
    - vim

- name: Install latexmk with apt
  apt: name=latexmk state=present
  become: yes
  tags:
    - vim

- name: Install language servers & linters with npm
  npm: name={{ item }} global=yes
  loop:
    - "typescript"
    - "typescript-language-server"
    - "vscode-langservers-extracted"
    - "eslint_d"
  tags:
    - vim

- name: Install efm-language server with go get
  shell: go get github.com/mattn/efm-langserver
  tags:
    - vim

- name: Clone Sumneko Lua Language Server
  git:
    repo: https://github.com/sumneko/lua-language-server
    dest: ~/.config/nvim/cache/lua-language-server
  tags:
    - vim

- name: Compile & Install Lua Language Server
  shell: cd ~/.config/nvim/cache/lua-language-server && git submodule update --init --recursive && cd 3rd/luamake && compile/install.sh && cd ../.. && ./3rd/luamake/luamake rebuild
  tags:
    - vim
