---
galaxy_info:
  role_name: flatpak
  author: ldonnez
  description: Flatpak is a utility for software deployment and package management for Linux. It is advertised as offering a sandbox environment in which users
    can run application software in isolation from the rest of the system.
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - all

dependencies:
  - role: packages
