- name: Install systemd-resolved with apt
  become: true
  ansible.builtin.apt:
    name: systemd-resolved
    state: present
  when:
    - (ansible_facts.distribution == 'Debian' or ansible_facts.distribution == 'Ubuntu')
    - ansible_facts.distribution_version is version('24.04', '>=')
  tags:
    - install
