name: Setup WSL ubuntu-22.04

on:
  workflow_dispatch:

jobs:
  setup_wsl_ubuntu:
    name: setup_wsl_ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Run run_setup_wsl_ubuntu.sh
        run: sh run_setup_wsl_ubuntu.sh
